version: "3.9"

services:
  mail:
    image: mailhog/mailhog
    environment:
      MH_AUTH_FILE: "/auth"
    volumes:
      - "./mail/auth:/auth:ro"
    networks:
      email:
        aliases:
          - mail
    ports:
      - "8025:8025"
      - "1025:1025"

  db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: dev
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    expose:
      - "3306"
    networks:
      database:
        aliases:
          - db
    volumes:
      - "./database/:/docker-entrypoint-initdb.d/"

  api:
    build:
      context: ./server
    networks:
      email: {}
      database: {}
      backend: {}
      frontend:
        aliases:
          - api
    expose:
      - "8082"
    environment:
      WEB_IP: 0.0.0.0
      WEB_PORT: 8082
      DOMAIN: https://localhost
      DB_PASSWORD: user
      DB_USER: user
      DB_NAME: dev
      DB_HOST: db
      DB_PORT: 3306
      EMAIL_PASSWORD: dev
      EMAIL_USER: dev
      EMAIL_HOST: mail
      EMAIL_PORT: 1025
      EMAIL_USE_TLS: "false"
    depends_on:
      - db
      - mail

  web:
    build:
      context: ./client
    networks:
      frontend: {}
    ports:
    - 80:80
    - 443:443
    environment:
      NODE_ENV: production
      API_HOST: api
      API_PORT: 8082
    depends_on:
      - api

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      database: {}
    depends_on:
      - db

networks:
  frontend:
    external: false
  backend:
    external: false
  database:
    external: false
  email:
    external: false
