version: "3.3"

services:
  api:
    image: tihlde/mplify-api:latest
    networks:
      net:
        aliases:
          - api
    environment:
      DB_PASSWORD: root_pw
      DB_USER: root
      DB_NAME: salt_linjeforening
      DB_HOST: localhost
      DB_PORT: 3306

  web:
    image: tihlde/mplify-web:latest
    networks:
      net: {}
    ports:
    - 8081:80
    environment:
      API_HOST: api
      API_PORT: 8080
    depends_on:
    - api

networks:
  net:
    external: false
